[package]
name = "jpegduperemover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rexif = "0.7.3"
walkdir = "2"
